apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
  - port: 80
    targetPort: http-port
    nodePort: 30080 