apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: marwansabry/go-app:latest
        ports:
        - containerPort: 80
          name: http-port
        env:
        - name: REDIS_HOST
          value: redis-service.db.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: APP_PORT
          value: "80"