apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: db
spec:
  clusterIP: None 
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: redis-port
    name: redis-port